/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula._4;

public class D {
    public static void main(String[] args) {
//        System.out.println("Hello World!");
/**
 *      Printa Hello World!
 */
        System.out./*Lero Lero*/println("Hello World!");
    }
}
