/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App;

import aula._4.D;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        D classUnderTest = new D();
    }
}
